### ISSUE TITLE
Which version of ArcGIS and VS should we be using?

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis#1]
Final versions of BAGIS suite to be released on ArcGIS 10.0. eBAGIS requires at least ArcGIS 10.2.2 as this version contains some API's for the cloud not present in earlier versions. ArcGIS add-ins are forward but not backward compatible. ie: a 10.0 add-in will run on 10.2.2 but not vice versa.

Visual Studio editions for 10.0:
Microsoft Visual Studio 2008 SP1 Visual Basic Express
Microsoft Visual Studio 2008 SP1 (C#, VB.NET) Standard, Professional, Team Edition
Microsoft Visual Studio 2010 (C#, VB.NET) Professional, Premium, Ultimate Edition
http://help.arcgis.com/en/systemrequirements/index.html#//01510000006n000000

Visual Studio editions for 10.2.x:
Microsoft Visual Studio 2010 (C#, VB.NET) Professional, Premium, Ultimate Edition
Microsoft Visual Studio 2010 Visual Basic Express
Microsoft Visual Studio 2012 (C#, VB.NET) Professional, Premium, Ultimate Edition
http://resources.arcgis.com/en/help/system-requirements/10.2/index.html#//01510000006n000000

**Comment by lbross** [comment]
Visual Studio editions for 10.3
Note that the professional versions are no longer free for students on DreamSpark. Once we move off of VS 2010, we either need to use the express versions or purchase the professional version.

Microsoft Visual Studio 2012, 2013 (C++, C#, VB.NET) Professional, Premium, Ultimate Edition
Microsoft Visual Studio 2012, 2013 Visual Basic Express
https://desktop.arcgis.com/en/desktop/latest/get-started/system-requirements/arcobjects-sdk-system-requirements.htm

**Comment by jdduh** [comment]
Microsoft now has a "community" level Visual Studio product. It seems to be an enhanced version of the Express version. Unless there is a reason for us to upgrade the VS version, we can continue using VS 2010 for now. It's good to know that 10.3 supports 2013 VB Express. I believe the Express version's functionality still supports our BAGIS implementation approach (i.e., we didn't use the Pro version's functions) (?)

**Comment by lbross** [comment]
I saw the "community" level product. Unfortunately it is not on the list of supported versions from ESRI. In the past, the ArcObjects SDK checks for a supported version and will not install without one. We need to know that when we start developing for 10.3, we will no longer be able to use VS 2010. Agreed that 2013 VB Express is sufficient for ArcGIS Add-In development.

I also use the web editing capabilities of VS 2010 which are likely missing from 2013 VB Express but that is a secondary issue.

**Comment by lbross** [comment]
Geoffrey talked to Gus at NWCC who says that we no longer have to support ArcGIS 10.0. However, Geoffrey would like the "final" versions of BAGIS-H and BAGIS-P to run on 10.0. Thus, we will continued development for these add-ins on 10.0.

**Comment by lbross** [comment]
We are working on compiling the add-ins for v10.5 per #60. Closing this issue. We will handle the ArcGIS version question on #60.
