### ISSUE TITLE
Add default web services button to settings form

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis#10]
This button would populate the following fields on the settings form with the default urls for image/feature services as listed [this page](https://sites.google.com/site/nwccspatialservices/ebagis/bagis-v3). Don't forget to set the preferred DEM to 30m.

Would also make sense to set the radio buttons and combo boxes to a default value since we should know them as we created the web services.

Question for Jarrett: How hard would it be to create a web service with name|value pairs for each of these values? Our other option is to distribute a configuration file but it would be harder to update if we need to make changes. With the service option, the administrator could make changes and client queries would always return the most current information.

**Comment by lbross** [comment]
@jdduh Jarrett has implemented the web services to maintain these files (PSU-CSAR/django-ebagis#49) and I need to update BAGIS V3 to use them. How would you like this to work for the .lyr file? Our current flow is:
1. Store the .lyr file at root of BAGIS folder
2. If user asks to load default settings, check for existence of .lyr file on user's computer
3. If it exists, ask the user if they want to overwrite from add-in

Do we want the same functionality? Except the file comes from the server instead of the add-in package?

**Comment by lbross** [comment]
Closing; Web services have been integrated into BAGIS v3. Documentation updated [here](https://sites.google.com/site/nwccspatialservices/ebagis/bagis-v3).

**Comment by jdduh** [comment]
Web services on the basins server to replace the services on atlas server. [See google site](https://sites.google.com/site/nwccspatialservices/ebagis/bagis-v3). Please update the default URLs on BAGIS V3.

http://basins.geog.pdx.edu/arcgis/rest/services

**Comment by lbross** [comment]
This is done and tested. I just needed to change the C:\ebagis\settings.yaml file on basins. Note that BAGIS v3 needs to use the bagis server alias instead of webservices because ArcMap tools can't handle 'services' in the name. I made a note of this on the google site.

**Comment by jdduh** [comment]
Sorry, I just update the URLs again for the three AWDB layers. We should use the layers in the ACTIVE folder.

**Comment by lbross** [comment]
No problem. I had to update the URLs again for the three AWDB layers because another part of the service name uses ACTIVE instead of ALL. I updated the google site as well. Nice that it is so easy to make this change on one server and not have to recompile the code!

**Comment by jdduh** [comment]
Set default PRISM webservice URL to:
http://bagis.geog.pdx.edu/arcgis/services/BAGIS_PRISM_1981_2010

The old 1971-2000 webservices are moved to:
http://bagis.geog.pdx.edu/arcgis/services/BAGIS_PRISM_1971_2000

**Comment by lbross** [comment]
@jdduh 
It looks like you changed the configuration file on basins which is correct. However, the names of the webservices are different than they used to be. For example: 'Prism_Precipitation_q4' is now 'Prism_1981_2010_Precipitation_q4'. This means that BAGIS V3 can no longer use the PRISM web services.

We can fix this one of two ways. I can update the service name enumeration in the BAGIS code. Or you can rename the web services. I prefer the latter because it means we can just rename the folder container for the next (future) set of PRISM data instead of re-compiling the application.

**Comment by jdduh** [comment]
All the PRISM precipitation imageservices are renamed based on the suggested (i.e., original) naming convention.
