### ISSUE TITLE
Update AOI Utilities Re-Clip selected layers button

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis#12]
To clip PRISM, Snotel, and snow course layers from web services

**Comment by lbross** [comment]
This is done

**Comment by jdduh** [comment]
Minor bug... After the re-clip tool removes the SNOTEL/Snow course layer from the AOI (before completing the reclip), the Vector Layers list is refreshed to reflect the change. However, after the re-clip tool completed the reclip, the Vector Layers list is not refreshed. As a result, the SNOTEL and snow course layers are not listed in the Vector Layers. User has to reset the AOI to update the list.

**Comment by lbross** [comment]
This applies to Basin Analyst > AOI Utilities form > Reclip selected layers button, correct? I remember seeing it earlier but can't currently reproduce. I also don't see anywhere in the code where the layers are removed from the Vector Layers list. Are you clipping from disk or web service? Anything else I might be doing differently?

**Comment by jdduh** [comment]
Sorry... I wasn't able to reproduce the bug. Yes, it was related to the Re-clip Selected Layers button.
