### ISSUE TITLE
BAGIS V3 - Options user notification and GUI improvements

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#14]
With the added functions to use web services in BAGIS, the GUI/User notifications need to be modified so that the users get immediate feedback. Here is an examples:

When opening the Options dialog, the tool checks and verifies the data specified in the settings. This  process might take a long time to complete when web services are used. Please add a progress bar (or an hourglass) to let users know BAGIS is doing something.

I will provide other examples when I get to use BAGIS V3 a little more.

**Comment by lbross** [comment]
This is fixed in the latest version. Besides the situation mentioned in the original ticket, I also added a progress indicator to the Default Settings button on the settings form. Other than that, I think we're covered by existing progress indicators.

@jdduh: what schem would you like to follow for versioning on BAGIS V3? I'm worried that if we just use the letters, we will run out soon. Once I have the version number, I will post a new version of BAGIS V3.

**Comment by jdduh** [comment]
How about we set the current "releases" as beta versions? I don't expect to see major changes on BAGIS down the road if NWCC buys into eBAGIS/cloud GIS. Also, we might need to, yet again, port the addins to ArcPro in the near future (BAGIS V4?)

**Comment by lbross** [comment]
Dropping letter from version designation. Next version will be 3.0-b1. Will increment "b" designation with future releases. First production release will be 3.0.

**Comment by lbross** [comment]
Found this when changing the version:
    Public Const BA_VersionText = "Basin Analysis GIS Ver 2.0 11/30/2012"
    Public Const BA_CompatibleVersion1Text = "Basin Analysis GIS Ver 1.0 7/4/2010"

Should I put Ver 2.0 into BA_CompatibleVersion1Text and 3.0 into BA_VersionText? This would mean that Ver 1.0 config files would no longer work unless the user manually tweaked the first line.

**Comment by jdduh** [comment]
Yes, please make the change. I assume that every time a user "saves" the settings the version text is updated.

**Comment by lbross** [comment]
I verified that the version text is updated to the current running version when the user "saves" the settings. Posted v3.0-b1 of add-in [here](https://github.com/PSU-CSAR/vb-bagis/releases/tag/3.0-b1) for testing. Closing.
