### ISSUE TITLE
BAGIS V3 Add Ref Layers cannot load pourpoint layer correctly

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#17]
The Add Ref Layers item on the BAGIS menu cannot load the pourpoint layer. See error message.

![image](https://cloud.githubusercontent.com/assets/11510708/19379040/ecd11f7c-91a4-11e6-8d7c-2020a661f72c.png)

However, when using the "Add Ref Layers to Map" button on the Options dialog window, the pourpoint is added to ArcMap correctly.

**Comment by lbross** [comment]
Fixed in next version of BAGIS v3

**Comment by lbross** [comment]
Fixed in v3.0-b2
