### ISSUE TITLE
AOI Tool - pourpoint selector

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#18]
After selecting a pourpoint from the list, the error message shows up when the Select button is clicked.

![image](https://cloud.githubusercontent.com/assets/11510708/19379742/6a8f39dc-91a8-11e6-92eb-e3eb354853a3.png)

This might be related to the awdb_id field, because this error message shows up later.

![image](https://cloud.githubusercontent.com/assets/11510708/19379803/bd841c34-91a8-11e6-84c1-c880c6b814b5.png)

The attribute table of the forecast point DOES contain valid data in awdb_id.

![image](https://cloud.githubusercontent.com/assets/11510708/19379837/f52ea60e-91a8-11e6-99a0-fdc49aead9ac.png)

The AOI creation process was able to complete despite these error messages.

**Comment by lbross** [comment]
Fixed in latest BAGIS V3 release
