### ISSUE TITLE
ArcGISCacheManager

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#19]
Can you do some research on this and see if this function can be disabled in VB scripts? I suspect that this feature caused a lot of the file or db "lock" problems in BAGIS (-H/-P). It's just a hunch.

**Comment by lbross** [comment]
I'm unable to find a VB .NET api that controls this service. The [most detailed information](http://gis.stackexchange.com/questions/4165/what-is-arcgiscachemgr-exe-and-why-does-it-have-a-lock-on-my-folder) I can find suggests that it is related to ArcGlobe. I tried the suggestions of changing the cache options and saving the .3dd but it didn't seem to have any effect. I suppose if you don't need ArcGlobe, you could uninstall it and see if that makes the problem go away. Okay to close this issue?
