### ISSUE TITLE
Update settings form to use services as data sources

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis#2]
See https://sites.google.com/site/nwccspatialservices/ebagis/bagis-v3 for analysis

**Comment by lbross** [comment]
Work layers instead of feature services when loading data or clipping. Test to see if we can get the information out of a layer file to clip a map feature service: url and layer number.

Update: I was able to write a custom GXDialog filter that allows us to select web feature services. Current plan is to store the REST URLs and use the REST API to load/clip data.

**Comment by lbross** [comment]
I added a table to the bottom of [this google page](https://sites.google.com/site/nwccspatialservices/ebagis/bagis-v3) with the services we need for the settings form and their urls (I think). Updated Jan 16.

Also, the 3 reference layers all appear to be combned into one map service and thus can only be accessed through a single layer path. The current UI has selections for each of the reference layers individually. No changes to current form. Test to see what happens if two layers are loaded.

**Comment by lbross** [comment]
Another question. The IGXFilters are different for web services that for the local file system. For example: GxFilterRasterDatasets vs GxFilterImageServers. Haven't been able to find a way to chain them together. Do we have 2 buttons side-by-side so user can choose local file or web? We could do custom filter that combines both but it may break if ESRI changes the underlying properties of file data sources. Also extra effort.

**Comment by lbross** [comment]
Filters can be chained using the IGxObjectFilterCollection Interface in this manner: 

```
    Dim rasFilter As IGxObjectFilter = New GxFilterRasterDatasets
    filterCollection.AddFilter(rasFilter, False)
    Dim imageFilter As IGxObjectFilter = New GxFilterImageServers
    filterCollection.AddFilter(imageFilter, True)
    Dim pGxDialog As IGxDialog = CType(filterCollection, IGxDialog)
```

**Comment by lbross** [comment]
Questions:
The filterCollection allows you to specify a default filter. Do we want to set the default to image server? raster? or no default?
There is no current plan for a 10m dem image service. Do you want me to enable this button to be able to choose image services? Or leave it as-is, raster only?

**Comment by jdduh** [comment]
Set default to local raster dataset. Please treat 10m DEM file browser the same as that for the 30m DEM, that is, make them having identical function. Basically, they are just the options to set two source DEM data.

**Comment by lbross** [comment]
Updated form to accept an imageService as source form 10m dem. Set default filters for both DEMs to local raster dataset.

**Comment by lbross** [comment]
Question: Updating gauge station layer to allow feature services. There is code that verifies the existence of awdb_id field. This field does NOT exist in the stations_usgs web service layer. I assume BAGIS needs this field during processing. Does this data have a different name in the web service layer?

**Comment by jkeifer** [comment]
I believe the awdb_id field is called usgs_id in the USGS station web service, but I don't have any data in front of me to compare, so I'm going off my rusty memory from way back when I made the import script.

**Comment by lbross** [comment]
What happens if the network is not available? Wait 30 seconds. Is there an API for checking to see if computer is connected to the internet. One test for all services. Second test is for individual url. Test on-by-one.

**Comment by lbross** [comment]
Added .NET function to check for network connectivity. Warn user if they aren't connected to the network. Did not add code to skip checking individual url's as architecture didn't support this well. Also mapped drives would also be affected so decided not to treat them differently.

**Comment by lbross** [comment]
Found that BAGIS settings form hangs the application when there are web service urls in the basinanalyst.def file and the corresponding ArcGIS server is non-responsive. Wrote function to verify if url connections are valid and to cache the results in a Dictionary so we don't try every url if the server is non-responsive. Implemented for 30m DEM and pourpoint layers.

Can't be sure this will work until server hangs again so will wait to implement for remaining layers.

**Comment by lbross** [comment]
The function to check web server availability works as designed. BAGIS still appears to hang while it is waiting for the connection to time out. It behaves the same as ArcCatalog when a server times out. Thus far haven't found a way to configure timeout length from the client side.

The program flow is awkward due to how the original code was written. The first time a server connection fails, the user gets a pop-up. Since BAGIS only tries once for each server it it fails, this message will only show once per server connection. Vectors and images have different urls one of each will be tested, even if on same server. The textbox for each failed data source will be blank on the form. The data source specific message will not be added to the long message that is returned from the function. The data source specific message is appended if an individual data source is tested and found to be unavailable. Hopefully the failures will be rare.

**Comment by lbross** [comment]
Revisited code in settings module. Able to adjust program flow so that data source specific error messages are appended to long return message. Also, in this function the text boxes are populated with the file path before it is validated so I didn't change that.

Need to test when atlas comes back online to make sure I didn't break anything.

**Comment by lbross** [comment]
Tested and working!

**Comment by jdduh** [comment]
NWCC folks weren't able to set PRISM web service folder as the source for BAGIS precipitation data. The same problem occurs on both basins and atlas servers. I cannot reproduce this problem on my computers. I will troubleshoot this problem the next time I visit NWCC. The other AWDB web services work normally.

![image](https://cloud.githubusercontent.com/assets/11510708/24305734/46a7c8b6-107b-11e7-947d-cc3a75d312f1.png)

**Comment by lbross** [comment]
Per my note earlier this week, ArcMap does not work when the server alias contains the text 'services', this the webservices alias will fail. Try bagis.geog.pdx.edu and it should work. This was my experience on my computer. Webservices failed with the same error message, but bagis was successful. I'm not sure why atlas would fail unless the service was unavailable.

**Comment by jdduh** [comment]
This bug is just related to the "Catalog location" object on ArcGIS 10.2.X, but not on ArcGIS 10.4.X. The web services on the webservices server work normally for servicing snotel and snow course data regardless of ArcGIS version. The PRISM precipitation services are no longer active on atlas server. The other AWDB services will be removed from the atlas server after March 30, 2017.
