### ISSUE TITLE
Remove the support for Weasel BASIN/AOI

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#21]
One of the key problem of BAGIS is its sluggishness. Especially for users who don't have a fast computer. After discussing with NWCC, they agree to remove the support for Weasel BASIN/AOI in V3. Hopefully this would speed up the folder checking/verification process.

Please modify the routines so that BAGIS only checks the folders for File GDB AOI/BASIN.

![image](https://cloud.githubusercontent.com/assets/11510708/19543575/6b0b2d38-962d-11e6-9974-e998e63983af.png)

**Comment by lbross** [comment]
Removed support for Weasel files from Basin Tool. It still seems slow to me. I did check through the code and didn't find anything else to change to make it more efficient. Looking up the DEM resolution is slow, I think.
