### ISSUE TITLE
Excessive refresh of the map when adding reference layers

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#22]
When I use the Add Ref. Layers to Map button on the Options dialog window or the Add Ref Layers menu item to display the reference layers, BAGIS redraws the screen 3 times. Please check the add featureclass/layer subroutine of BAGIS and see if it's possible to disable the refresh before the last layer is added to ArcMap.

For users with slow computers and who use a big dataset (or a web service) as the reference layer, the process could take several minutes to complete.

**Comment by lbross** [comment]
I think this is fixed. I removed one extra refresh but couldn't find a third. I removed the second one I found and it seems to work correctly. Not sure where the actual refresh is occurring. Please test this when it is released to ensure it is working as desired.
