### ISSUE TITLE
AOI Utilities: Re-clip Selected Layers

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#23]
The Re-clip Selected Layers button doesn't have any function. 

![image](https://cloud.githubusercontent.com/assets/11510708/19991092/f272ad14-a1ef-11e6-8e78-5a18699a662a.png)

Also, please hide the Update Weasel Info button. BAGIS V3 will no longer support Weasel AOIs.

**Comment by lbross** [comment]
Somehow the CmdReClip_Click sub got disconnected from the click event. I reconnected them and cleaned up a couple of things. I didn't write this function initially. I tested it with both file and webservice layers and it worked. Update Weasel Info button and accompanying code have been removed. This will be in the next release of BAGIS V3.
