### ISSUE TITLE
Site Scenarios tool error - empty feature/unable to find intermediate file

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#24]
The AOI has 104 snow course sites and 23 SNOTEL sites. See attached document for error message. I'm not sure what might have caused the first error message. The AOI is a rectangular shape that covers a huge area (the AOI file size is 2.6 GB). The test_aoi.zip file contains the AOI boundaries. You can use the "Create AOI from a shapefile" tool to generate the AOI. The layers.gdb.zip contains the SNOTEL and Snow Courses featureclasses of the AOI.

[test_aoi.zip](https://github.com/PSU-CSAR/vb-bagis/files/629205/test_aoi.zip)

[BAGIS_SiteScenarios_ErrMsg.docx](https://github.com/PSU-CSAR/vb-bagis/files/629201/BAGIS_SiteScenarios_ErrMsg.docx)

[layers.gdb.zip](https://github.com/PSU-CSAR/vb-bagis/files/629203/layers.gdb.zip)

**Comment by lbross** [comment]
BA_Raster2PolygonShapefile is failing for one or more sites in BA_ExtractRepresentedArea. I was not trapping this failure. No vector output was created to merge with the other sites. The merge tool tried to add a layer to the merge that didn't exist so it failed. I have added error handling that excludes failed sites from the merge and notifies the user.

Do we want to go further than this? RasterToPolygonShapefile uses the IConversionOp, one of the old geoanalyst tools. We have had trouble with these in AGS 10.2.2. Could switch to the GP tool but it would be slower. I can also try to dig into the site(s) that are failing. This will take some time due to the number of sites in this example and trying to trap the specific site(s).

**Comment by jdduh** [comment]
Can you track down what was causing the shapefile to not be generated? Do you know which point is "Enderby_2"? I only see "Enderby", but not "Enderby #2" in the snowcourse layer. The SNOTEL doesn't have an "Enderby."

**Comment by jdduh** [comment]
OK, Enderby_2 is for Enderby. The shapefile does exist in the temp output. I will look further.

**Comment by jdduh** [comment]
Does BAGIS use the elevation data from the snow course/SNOTEL attribute tables or from the DEM? I found many elevation values (in feet) in the snow course attribute table very different from the DEM elevation (in meters). Here is a list of some of the snow course sites: Moses Peak, Klesilkwa, Thunder Basin, Moses Mtn #2, etc. If the elevation values used were from the attribute table, then the represented areas for these sites will have null geometry.

**Comment by jdduh** [comment]
The "Extract Values to Points" tool can transfer the DEM elevation values to the point featureclass.

**Comment by lbross** [comment]
Thank you for researching. Yes. The elevation data currently comes from the attribute tables. How would you like to handle this?
1. Add a new column to the feature class(es) for DEM elevation
2. Use the "Extract Values to Points" tool to populate this field
3. If the field already exists, we don't have to populate it again which might save time

Or do we use the "Extract Values to Points" tool every run?

Do we do this just for the snow course sites? Or also for Snotel?

**Comment by jdduh** [comment]
The steps are correct. Populate the DEM elevation values to both SNOTEL and snow course layers. The Extract Values to Points tool should only be used once, when the attribute tables of the two layers don't have the DEM elevation field.

**Comment by jdduh** [comment]
Please let me know the field name you want to use for the DEM elevation. You probably can reuse the "BA_SELEV" field. That could minimize the need to update other BAGIS tools. If this is the route you want to go, then the "Extract Values to Points" process should occur during the AOI creation phase (i.e., when SNOTEL and snow course layers are clipped to the AOI).

**Comment by lbross** [comment]
Using "BA_SELEV" is fine. I can create/populate the column initially during the AOI creation phase (both from a basin and a shapefile) We also need to check for this column before any tool that needs the data to account for existing AOIs. If the column is missing, we need to run the "Extract Values to Points" process. Obviously this needs to happen with the site selection tool. Does the Generate Maps tool use elevation from the snotel, snow course sites? I recall that it does. 

Can you think of any other tools?

**Comment by lbross** [comment]
Actually, is re-using "BA_SELEV" a good idea? Can we trust that the data is valid if the column exists on the table?

**Comment by jdduh** [comment]
You are right! But, BA_SELEV is also used in the basin analysis tool (i.e., for generating the maps and Excel tables/graphics). There is a tool in the AOI Utilities form for reclipping the snow course and SNOTEL layers to the AOI. Maybe we can ask users to reclip these layers to update these layers' BA_SELEV values.

**Comment by lbross** [comment]
So we need to add code to the AOI Utilities reclip button to recalculate the BA_SELEV field using the "Extract Values to Points" process? Do we always want to do this or add a checkbox to make it optional? It looks like the field is currently the elev field converted into meters. Do we want to record our updated elevation in meters? I am already using the BA_SELEV as the source of the elevation data so nothing will need to change there.

Is updating the reclip button the only change that needs to be made now? Or do we also want to use "Extract Values to Points" during the AOI creation phase?

**Comment by jdduh** [comment]
We need to update both the reclipping and the clipping during AOI creation if BAGIS doesn't use the same subroutine. Yes, always use metric system in BAGIS internally. I doubt it would take a long time to execute the "Extract Values to Points" tool. We can just update the BA_SELEV values whenever an AOI is created or the Reclip tool is used. (Note: the reclip tool deletes the layers first, so there is no easy way to not update the BA_SELEV values.)

**Comment by lbross** [comment]
The "Extract Values to Points" tool creates a new vector with all of the attributes from the original vector plus a new column called 'RASTERVALU' that contains the elevation value. What field do you recommend I use to join the original attribute table with the new one. I'm inclined to just use the OBJECTID. Is this acceptable?

Alternatively, after the tool runs, I could copy the values from RASTERVALU  to BA_SELEV, delete RASTERVALU column, delete the original vector, and rename the new vector as the snow course layer.

Thoughts?

**Comment by jdduh** [comment]
I'm not sure if objectid is a persistent field. It seems the alternative method is more bug-proof, that is, "copy the values from RASTERVALU to BA_SELEV, delete RASTERVALU column, delete the original vector, and rename the new vector as the snow course layer." If you create the original layer using a temporary name, then you can save the rename step.

**Comment by lbross** [comment]
Decided to validate our proposed solution manually before coding to see if it solves the problem. It does. However, I get the attached error when the maps display. Anything to worry about? Will move forward with recalculating BA_SELEV.

![failedtoload](https://cloud.githubusercontent.com/assets/11527966/21111921/849fe6f8-c058-11e6-864b-934d08da8ae4.jpg)

**Comment by lbross** [comment]
This is almost working. I saved off the original snotel layers before re-clipping running my code. I compared the 2 layers and noticed that my new layer is missing some columns. I think this may be due to different source Snotel data but thought you should take a look. Snow course looks good.
[Snotel.xlsx](https://github.com/PSU-CSAR/vb-bagis/files/647357/Snotel.xlsx)

**Comment by jdduh** [comment]
I've never encountered the display error that you mention. Let's see if that does affect the site scenario tool's display function. The SNOTEL and snow courses layers do not have a standard set of attribute fields. In theory, both layers can be any point featureclass that has an elevation field. That's why BA_SELEV and BA_SNAME were used.

**Comment by lbross** [comment]
After I reclipped the layers with the correct BA_SELEV, I did not get this display error so hopefully the users won't either. Won't worry about it for now ...

**Comment by jdduh** [comment]
A minor bug to be fixed. The Site Scenario tool should become enabled when an AOI is selected. Currently, user must go through the Generate Maps steps to activate the Site Scenario tool. I don't think this tool has any dependency on the Generate Maps output.

![image](https://cloud.githubusercontent.com/assets/11510708/21215161/378d9eac-c254-11e6-99f0-c38fde8618ce.png)

**Comment by lbross** [comment]
Actually there is a dependency. The elevzone layer is used as a base layer when displaying the site scenario maps. Let me know if you want to change this.
