### ISSUE TITLE
AOI Tool Warning: Not connected to the network

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#28]
Got this message a couple time during AOI creation. BAGIS doesn't use any network layer in the settings.

![image](https://cloud.githubusercontent.com/assets/11510708/22359247/647111b6-e3fa-11e6-902c-6d6adb2879b1.png)

The message also shows up when opening the Settings dialog window (i.e., Options menu item) after the AOI was created. There is no warning message before the AOI was created.

**Comment by lbross** [comment]
The difficulty is that I don't know if BAGIS has any network layers in the settings until I read the settings so I always perform the check. I can make it more refined by setting a global variable and only checking the first time there is a network layer in the settings. Obviously, network connectivity could change during a BAGIS session but we can't have it both ways. 

Is this the desired behavior? To check the first time there is a network layer in the settings, display the warning, and not check again?

**Comment by jdduh** [comment]
Yes, check the first time if there is a network layer in the settings, then display the warning, and not check again. Also, change the warning message to "ArcGIS is not connected to the network. If you use any web services in BAGIS, then these web services are not available for BASIN creation."

**Comment by lbross** [comment]
This has been resolved in BAGIS and will be in the next release.
