### ISSUE TITLE
Elev-Precip Correlation Tool - Elev unit doesn't support feet

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#31]
When user selects feet as the analysis unit, the output elevation values are still in meter. The chart's axis unit are set correctly. As a result, the scatterplot doesn't fall in the range of the chart's display area.

**Comment by lbross** [comment]
How do you recommend fixing this? Apply the conversion factor before writing the values to the Excel table? It seems a lot of work to update in the GIS layers.

**Comment by jdduh** [comment]
Yes, do the conversion when writing values to the Excel table.

**Comment by lbross** [comment]
I applied the conversion factor that is used by the rest of the maps form to both the aoi and site elevations. This will be fixed in the next version of BAGIS V3
