### ISSUE TITLE
Elev-Precip Correlation Tool - values of partition layer were not generated

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#32]
The spreadsheet headings were generated without any values.

![image](https://cloud.githubusercontent.com/assets/11510708/24272549/071fe11a-0fdb-11e7-84ba-05a307d8af77.png)

![image](https://cloud.githubusercontent.com/assets/11510708/24272568/15639834-0fdb-11e7-9e48-66456f54c6b8.png)

The part_ layer seems correct.

![image](https://cloud.githubusercontent.com/assets/11510708/24272613/445a4412-0fdb-11e7-9555-44c96c100592.png)

**Comment by lbross** [comment]
Do you remember what you did prior to clicking the 'Tables' button? I don't doubt that there is a bug somewhere but I can't recreate this behavior.

**Comment by jdduh** [comment]
Do I need to run 4. Generate Zones again after setting a layer for the Elev-Precip Attribute Layer? The GUI for Elev-Precip Correlation panel was disabled when I begin with a new AOI. If re-running 4. Generate Zones is required, then the GUI should be enabled.

![image](https://cloud.githubusercontent.com/assets/11510708/24308987/4cae3892-1087-11e7-9923-d536356e31bc.png)

**Comment by jdduh** [comment]
Also, the two Exists captions look odd on the form. Please hide them. I suggest that we use blue as the font color on the two labels so that the users know they are messages, not GUI labels.

**Comment by jdduh** [comment]
After running 4. Generate Zones, the Elev-Precip Correlation panel was still disabled. I had to close and reopen the form to activate the panel.

![image](https://cloud.githubusercontent.com/assets/11510708/24309576/9cbe3510-1089-11e7-9a16-55877f696ae8.png)

**Comment by lbross** [comment]
I knew there had to be more to it. I didn't test with a new AOI...

1. You do need to run 4. Generate Zones again after setting a layer for the Elev-Precip layer. This is related to my question on issue #33 about using the same GUI logic for Elev-Precip as for aggregation.

2. The GUI for Elev-Precip Correlation panel is disabled (incorrectly) when beginning with a new AOI. I am using the AOI_HasSNOTEL and AOI_HasSnowCourse flags to check to see if these layers exists but upon closer examination these flags refer to the zones files which won't be there in a new AOI. This is a bug I will fix.

3. Exists is a design placeholder. It should not appear. The logic needs to be fixed for when the form loads. VB is odd about the font color on a disabled panel. If the panel is disabled, the font is always black unless you take extraordinary measures. I will take another look to see if there is an easy way to make it blue.
