### ISSUE TITLE
Compile PRISM dataset for 1981 - 2010

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis#36]
Data available on basins at D:\projects\gisdata\prism-gisdb
Suggested steps:
1. Convert ascii to raster
2. Define projection
3. Reproject to Albers (BAGIS default)
4. Add all of Jan together and divide by 30
5. Repeat for other 11 months
6. Sum months for quarterly and annual aggregation
7. Output should be grid format and match current naming convention

**Comment by lbross** [comment]
Research downloading the monthly normals from OSU
http://www.prism.oregonstate.edu/normals/

**Comment by lbross** [comment]
All of the file locations mentioned below are on basins:
I am downloading the .zip files from OSU to: D:\projects\gisdata\prism-gisdb\source-osu\zips
I unzip each zip file to: D:\projects\gisdata\prism-gisdb\source-osu\ascii where there are subfolders for each month
I created a new toolbox here: D:\projects\gisdata\prism-gisdb\PRISM_Tools.tbx
The name of the model is: Import_PRISM
The outputs generated from the model are here: D:\projects\gisdata\prism-gisdb\output where there are subfolders for each month.

So far I have only done jan and feb as examples. @jdduh please let me know if these look good and I will process the remaining 10 months. It goes pretty quick with the model.

**Comment by jdduh** [comment]
The two GRID data sets look good. The projection and data format are following the data spec. Please proceed with the other layers. 
q1 = jan + feb + mar, etc.
annual = q1 + q2 + q3 + q4

**Comment by jdduh** [comment]
You might want to use a folder name that clearly indicates the data set is for 1981 to 2010 on the server. Also, when you have created all the GRIDs, please save a copy of them in .img format for the webservices.

**Comment by lbross** [comment]
Per your suggestion, I have renamed the input and output folders:
D:\projects\gisdata\prism-gisdb\source-osu-1981_2000
D:\projects\gisdata\prism-gisdb\output-1981_2000

I will add the .img creation to the model. Where would you like me to store them? And what naming convention would you like to use? Alternatively, you can provide the directory where the 1971-1990 images are and I will follow that convention.

**Comment by jdduh** [comment]
The BAGIS "static" datasets are stored at D:\projects\gisdata\bagis-static. I have created a folder called "USPrism_1981_2010." You can find the 1971 to 2000 dataset in the "USCanadaAKPrism" folder.

**Comment by lbross** [comment]
I have processed the data for jan - jun including the quarterly sums if you want to take a look. I will likely finish up the remainder of the months tomorrow unless I hear from you that there is a problem.

**Comment by jdduh** [comment]
Thanks! The produced layers look good.

**Comment by lbross** [comment]
All of the precipitation data should now be available on basins! Do we have to do something similar for the precipitation data for BAGIS-P? This data is also available on the OSU website. I think it is used by some of the models.

**Comment by jdduh** [comment]
Thanks for compiling the 1981-2010 normal precipitation data. BAGIS-P only needs tmin and tmax for July and August. Please compile these layers and put them in a FileGDB. You can name the layers as:
PRISM_tmax_july_1981_2010
PRISM_tmax_august_1981_2010
PRISM_tmin_july_1981_2010
PRISM_tmin_august_1981_2010

**Comment by lbross** [comment]
Temperature data is done. It appears to be supplied and stored in C. I compared the values to the previous normals. The data is stored here: D:\projects\gisdata\bagis-static\PRISM_temp_1981_2010.gdb
