### ISSUE TITLE
Auto Pseudo-Site tool calculation verification

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#38]
I create two auto pseudo sites. The first one was created without any additional constraints. The 2nd one, shown in purple, has an elevation and proximity constraints. The proximity is set to be within 2500 meters of the stream layer. However, the location of the 2nd site seems problematic. I would expect to see a site near the hand-drawn blue X. Let me know what you think.

![image](https://cloud.githubusercontent.com/assets/11510708/26187673/8d52d2a2-3b4f-11e7-89b8-5ed5c0e7a3e3.png)

**Comment by lbross** [comment]
I think this is working as designed, but perhaps not as desired. In this case BAGIS unions the represented area (red), undesired elevation area (green), and undesired proximity area (orange). It then finds the pixel the furthest from this total undesired area. On your map, the desired area is represented by light blue so you would expect the site in the middle of a large blue patch (where it is). Your blue X is very close to the undesired proximity area (orange).

**Comment by jdduh** [comment]
The preferred logic should be:
1. Create the Euclidean distance raster
2. Remove from the distance raster the areas that are specified in the constraint(s), i.e., set the cells to NULL or zero
3. Find the location that has the largest distance value

Only existing represented areas are used in the distance calculation, not the constraint layers.

**Comment by jdduh** [comment]
NWCC is interested in having the capability of specifying multiple proximity/location (i.e., #41) constraints. Please consider this request when thinking about the implementation.
