### ISSUE TITLE
Site Scenarios Map - inaccurate "not represented" layer

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#39]
It seems that the Not Represented layer covers the whole AOI (as shown on the first image), which is incorrect. The 2nd image shows the AOI's represented area.

![image](https://cloud.githubusercontent.com/assets/11510708/26263602/54b48edc-3c8e-11e7-9e3c-04710c112b5b.png)

![image](https://cloud.githubusercontent.com/assets/11510708/26263770/ee3c4c20-3c8e-11e7-95eb-89694e126b7b.png)

**Comment by lbross** [comment]
The Not Represented layer is the aoib raster. The logic is that the represented feature classes will cover portions of the aoib raster so the part of the aoib raster that is visible is the non-represented layer. If the user uses the buttons to select a site scenario map, they should never see this layer without a represented layer on top. 

We use the same logic on the auto-site map. The desirable area (light blue) is a base layer and is everything that is not covered by one of the excluded layers. However, in this case we talked about the user manipulating the layers in the TOC to evaluate the different constraints which is what we DON"T want them to do on the site scenario maps. Maybe we need to add map buttons to turn the constraint layers on/off for the auto-site map?

**Comment by jdduh** [comment]
Experienced ArcGIS users, such as Gus, will probably manipulate the layers in the TOC. If we don't use "not represented" and "desirable" layers in any analysis, then we might just sacrifice aesthetics by removing these two layers. Otherwise, we need to create the real "not represented" and "desirable" layers.

**Comment by lbross** [comment]
I propose leaving the "not represented" and "desirable" layers on the map for aesthetics but we can rename them 'AOI'. The map doesn't look as nice with just the hillshade.

**Comment by jdduh** [comment]
Sounds a good solution. Please rename the layers to more appropriate layer names.

**Comment by lbross** [comment]
This is done and will be in the next release of BAGIS V3. Also added code to remove layers from pre-existing site scenario or auto-site maps before loading new map.

**Comment by jdduh** [comment]
The renamed background AOI layer is turned off when the representation map menu items are selected. Based on the original design, the AOI layer should be turned on.

**Comment by lbross** [comment]
Am I allowed to change my mind about using the background 'AOI' layer for the site scenario maps? For scenario 1, scenario 2, and site representation maps we are already using the elev zones layer to cover the hillshade and show the spatial extent of the AOI. I propose that we do the same on Difference of Representations map and do away with the solid color AOI base layer altogether. If you think the color gradations on the elev zones map are distracting then we could discard it and use the AOI base layer. Either way, all 3 types of maps should use the same base layer.

**Comment by jdduh** [comment]
The maps without the AOI background look good. You can remove the AOI background from the layer out if it's not used.

**Comment by jdduh** [comment]
This is just an observation, not a bug report - the map tool on Auto-Pseudo Site tool still displays the AOI boundary as the light-blue background. The background does make the map look better.

**Comment by lbross** [comment]
Updated the 'Difference in Representations' map to use the elevation zones layer instead of the monotone AOI layer to colorize the hillshade. Also adjusted the colors for scenario 1 and scenario 2 areas on this map as they blended in with the elevation zones map. I don't plan to change the light-blue background on the auto-site tool.
