### ISSUE TITLE
Create AOI from shapefile needs to be updated

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis#4]
When settings is able to use map services, this tool needs to be updated to use them as well in case the settings file is pointed to map services.

**Comment by lbross** [comment]
Started by updating dem clipping to accomodate an image service.

**Comment by lbross** [comment]
Need to handle case where supplemental layer is in properties file but is inaccessible when clipping occurs:
System.InvalidCastException: Conversion from string "Conversion from string "Missing " to type 'Integer' is not valid. ---> System.FormatException: Input string was not in a correct format.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
   --- End of inner exception stack trace ---
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
   at BAGIS.frmCreateAOIfromExistingBND.cmbRun_Click(Object sender, EventArgs e) in C:\workspace\vb-bagis\src\AOI\frmCreateAOIfromExistingBND.vb:line 922
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by lbross** [comment]
This is done. Outstanding issue #7 covers snap to raster. Not sure if this is lining up correctly.

**Comment by jdduh** [comment]
The clipping needs to be performed on the buffered AOI boundary, i.e., aoib_v. The current clipping is only on the envelope of the AOI. Note: the GUI allows users to set a custom buffer distance. Please use the buffer distance to create the aoib_v and recalculate the correct clipping extent.

**Comment by lbross** [comment]
Not sure what the problem is here. I ran the tool twice. Once with the buffer AOI checkbox unchecked, and once with it checked and a buffer of 500 m. In the unbuffered test, aoi_v and aoib_v were the same size and the basis for the clipping. In the second test, aoib_v was larger and the filled_dem was also larger with a larger extent. Can you elaborate?

**Comment by jdduh** [comment]
Getting this error message when using the tool. The problem occurs only when the source DEM is from a image service.

![image](https://user-images.githubusercontent.com/11510708/26953379-cadf3410-4c5e-11e7-92ed-4f29afbae680.png)

**Comment by lbross** [comment]
Found the bug where clipping from an image service was not using the correct AOI boundary. I did not get the exception above but will try expressly setting the workspace in that subroutine to the AOI root. I did notice that when clipping from an image service, you get the whole rectangle rather than just the AOI boundary. Does this need to be changed?

**Comment by jdduh** [comment]
It would be nice if you can clip the DEM to the buffered shape, but I remember that you told me that it's not possible (or straightforward).

**Comment by lbross** [comment]
What I can do is execute our BA_ClipAOIRaster() function after we extract the AOI rectangle from the image service. This will, obviously, take longer during processing but should be easy to implement. Let me know if you want to add this. Also if I should add this step to the PRISM layers that are clipped from web services?

**Comment by jdduh** [comment]
I believe that you have used definition query to hide the areas outside the AOI boundary when displaying maps. So, it's not a big problem to not clip out the rasters using the AOI buffered boundaries. However, if it's not too much trouble to implement the routine, then please implement the clipping for the DEM and the PRISM image services.

**Comment by lbross** [comment]
Just finished changes to clip DEM and PRISM rasters derived from an image service to the AOI boundary, not just the envelope. This will be in the next release of BAGIS v3.
