### ISSUE TITLE
Generate Maps - new slope classification

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#40]
Requested by NWCC to have a new slope classification for the Generate Maps tool. The new class intervals are:

Flat - 10%
10% - 20%
20% - 30%
30% - 40%
40% - 50%
50% - 75%
75% - 100%
100% - 150%
150% - 200%
. > 200%

(Note: remove the . in front of the "> 200%", GitHub renders ">" as a special formatting character. ) 

The current intervals are shown on the map below.
![image](https://cloud.githubusercontent.com/assets/11510708/26264055/34861296-3c90-11e7-9be4-ab409ba74052.png)

**Comment by lbross** [comment]
This is done and will be in the next release of BAGIS v3.
