### ISSUE TITLE
Auto pseudo site tool - "Location" constraint using raster data

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#41]
Adding a new "Location" constraint that allows users to select a discrete raster layer and specify a list of cell values for limiting the auto site search. The GUI should be similar to BAGIS-H's parent HRU layer function. It would also be desirable to list all the attribute fields, instead of just the cell value, on the value list to make the selection of value(s) easier. See #42 for raster layer list spec.

![image](https://cloud.githubusercontent.com/assets/11510708/26266211/4a8bc032-3c99-11e7-8dd2-39bcae7ca5b0.png)

**Comment by lbross** [comment]
Should the values specified be included or excluded in the search?

**Comment by jdduh** [comment]
The selected values should be included (i.e., exclude not selected values) in the search. Change the label caption to "Limit the search on selected zones." If no value is selected, then prompt a warning message and uncheck the Location checkbox.

**Comment by lbross** [comment]
Looking at the sample GUI on p. 6 of site scenario prototype. Do we need to have the checkbox on the far left-hand side? It would look cleaner without. If the layer is in the grid, it would be used. Also, I am going to experiment with putting the pick lists inside the grid and see if that works.

**Comment by jdduh** [comment]
Deletion is performed on one entry at a time. There is no need to have the checkbox.

**Comment by jdduh** [comment]
The GUI design is spot-on and the tool seems to work correctly. Here are some minor issues.

1. Partially obscured GUI.
![image](https://user-images.githubusercontent.com/11510708/27501461-53f9ecc6-5822-11e7-9d92-df849df4997e.png)

2. Activation of the delete and edit buttons. Users must click on the first (heading) column to activate the delete and edit button. Is there a way to activate the button when any cell in the list is clicked? See the two activation condition images below.
* Heading column (i.e., whole row) is selected
![image](https://user-images.githubusercontent.com/11510708/27501514-c452fda0-5822-11e7-89bc-f672dbe7c4f0.png)

* Only a cell is clicked (please enable the delete or edit button as well) 
![image](https://user-images.githubusercontent.com/11510708/27501560-035825e8-5823-11e7-918d-65ecb3c7ebcb.png)

3. Add the following text to the Frame caption "Location - limit search in the intersection of the conditions specified below." Similar text also needs to be added to the Proximity constraint. 
![image](https://user-images.githubusercontent.com/11510708/27501686-beb898fe-5823-11e7-8d8b-37706fcf03d8.png)

4. Add the following text to the tool description:
". The overlay of multiple constraints is based on AND (i.e., intersect) operation."
![image](https://user-images.githubusercontent.com/11510708/27501794-74c6717a-5824-11e7-8470-a16f89227068.png)

**Comment by jdduh** [comment]
A potential issue (or is it just me?) - the "Done" button captions should be renamed to something else, like "Close" or "Exit." Every time when I was done setting up the constraints, I naturally clicked on "Done," which cancels my last setup.

![image](https://user-images.githubusercontent.com/11510708/28645665-4accb254-7213-11e7-96ec-64ddfdf32e94.png)

**Comment by lbross** [comment]
I can rename the button to "Close". In addition, I could close the selection window when the 'Save' button is pressed. The user would have to open the form again to add another constraint but my guess is they will most often use one layer at a time. Thoughts?

**Comment by jdduh** [comment]
Please close the selection window after the 'Save' button is pressed. Rename 'Done' to 'Cancel.'

**Comment by lbross** [comment]
I have updated the functionality as requested. I think this makes the form more usable. This will be in the next release of BAGIS V3.

**Comment by jdduh** [comment]
Unable to open the Site Scenario tool. The menu item remains disabled no matter what.

![image](https://user-images.githubusercontent.com/11510708/29760391-0dbb89ca-8b78-11e7-8c86-96c6f97a2c1d.png)

**Comment by lbross** [comment]
I have not encountered this issue. My usual workflow is to set the current AOI using the AOI Info tool. If the maps tool has been run then the Site Scenarios tool should be enabled. BAGIS checks for the presence of the analysis.gdb\elevzone layer before enabling the Site Scenarios button as this is the base layer for all of the site scenario maps. Next troubleshooting steps would be:

1. Check for the presence of the elevzone layer in the AOI. If this layer isn't being created, we may have a bug there.
2. Let me know if you are following a different path to enable the Site Scenarios tool
3. If neither of the above works, can you upload the AOI so I can try to replicate? You didn't say if this is with one or many AOI's. If many, we may have an ArcGIS version issue :-(

**Comment by jdduh** [comment]
This problem went away... I'm not sure what was causing it. I did notice that after updating a new add-in, the add-in usually won't behave 100% correctly the first time ArcMap was restarted. Users needed to restart ArcMap again to clean up some of the leftover information.

**Comment by lbross** [comment]
The process that has worked for me in the past is:

1. Use the ArcMap add-in manager to delete the old add-in
2. Restart ArcMap
3. Install the new add-in

But maybe we need to add a step 4 to restart again? Glad the problem went away.
