### ISSUE TITLE
Auto pseudo site tool - expand layer list folders

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#42]
This request is related to the listing of available raster layers for #41, the Location constraint. Is it possible to include elezone, preczone, slpzone, and aspzone (or maybe even stelzone and scoszone) in the list? These layers should be available by the time when users access the site scenarios tool.

![image](https://cloud.githubusercontent.com/assets/11510708/26264354/62c10af2-3c91-11e7-9f68-d43423ac9210.png)

**Comment by lbross** [comment]
We will list any discrete rasters that are in the layers.gdb and the 5 layers from the analysis.gdb that are in the original issue description. We will check for the existence of the analysis.gdb layers prior to adding them to the pick list.

**Comment by jdduh** [comment]
Rasters in the layers.gdb are not shown in the list.

**Comment by lbross** [comment]
Are the missing rasters discrete? Only discrete rasters are included.

**Comment by jdduh** [comment]
I use west_covtype in the test. It looks like a discrete raster.

![image](https://user-images.githubusercontent.com/11510708/27502002-beae3a9c-5825-11e7-9871-798ff100bbf1.png)

**Comment by lbross** [comment]
Found the bug. This will be in the next release of BAGIS V3.

**Comment by jdduh** [comment]
The rasters in the layers.gdb do show up now. However, it also includes continuous rasters that don't have attribute table.

![image](https://user-images.githubusercontent.com/11510708/27567000-dd430d14-5a9d-11e7-837f-e7138e2f0406.png)

**Comment by lbross** [comment]
This is a strange case. We have a BA_IsIntegerRasterGDB function that uses IRasterProps.IsInteger to determine if a raster is discrete or continuous. All of the values in cov_den are integers but it does lack an attribute table. I added another check to make sure the raster has an attribute table before adding it to the list. This will be in the next release of BAGIS v3.
