### ISSUE TITLE
Auto pseudo site tool - verification of key strokes

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#43]
The field validation should occur when the user clicks on the "Find Site" button. The current implementation makes it difficult to move from one field to another without entering a valid value (e.g., when the user wants to abandon an operation). Also, the current implementation won't treat ".1" as a valid value.

**Comment by lbross** [comment]
This is done for elev, precip, and a single proximity layer. It will need to be updated when adding multiple proximity and/or location layers.
