### ISSUE TITLE
BAGIS V3 version and release information

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#44]
To simplify the version update tasks, please keep the add-in version information the same and only update the BAGIS About dialog window. Before the final release of BAGIS V3, set the add-in version text to "3.0 Beta" for the intermediate releases.

![image](https://cloud.githubusercontent.com/assets/11510708/26514365/386e189a-4226-11e7-989a-6a9f82450e87.png)

The image below shows the version and Release text in the About dialog window. The information must be updated for every new release.
![image](https://cloud.githubusercontent.com/assets/11510708/26514403/6402657e-4226-11e7-9106-b7ed0ec9ac99.png)

**Comment by lbross** [comment]
For clarification's sake:
1. For major releases only we will update the add-in version information. Currently, the version should be at '3.0 Beta'. The date will not change until the final release.
2. For minor releases we will update BA_SubVersionText. This includes the version number AND the date
3. For bug fixes that don't even warrant a minor release number update, we will ONLY update the date portion of BA_SubVersionText. This ensures that the user can tell if they have the correct version

Sound okay?

**Comment by jdduh** [comment]
Sounds good. Please use the version protocol that you propose.

**Comment by jdduh** [comment]
Once we get a no-bug confirmation from NWCC, update the version number to 3.1 for the final release (date TBD). This includes the add-in version information and the information on the About dialog window. Is the text "Basin Analysis GIS Version 3.0 04/30/2016" a key for any log/definition file?

**Comment by lbross** [comment]
We will need to give NWCC at least one new version because I am fixing some bugs that we already know about. Yes, the text "Basin Analysis GIS Version 3.0 04/30/2016" a key for both reading in the both the bagis settings and map settings. There is also a BA_CompatibleVersion1Text that is a key used the same way. It is currently set to Basin Analysis GIS Ver 2.0 11/30/2012. 

If we think BAGIS V2 is no longer in use, we could bump 3.1 into the BA_CompatibleVersion1Text and make v3.1 the primary key.

**Comment by jdduh** [comment]
Sounds a good plan to replace V2 with 3.1 for the BA_CompatibleVersionText. What's implication of using V3.1 as the primary key? Meaning all the log/definition files will have it in them?

**Comment by lbross** [comment]
There are two project variables to control the versioning: BA_VersionText and BA_CompatibleVersionText. BA_VersionText is written as the first line of the BAGIS settings file and the maps settings file. I recommend BA_VersionText to the newest version and BA_CompatibleVersionText to the previous version as long as you are okay with AOI's last touched by BAGIS V2 no longer loading.

Of course, all you have to do to fix it is change the first line of the file to the updated version text.

**Comment by lbross** [comment]
BA_VersionText is now Basin Analysis GIS Ver 3.1 08/01/2017
BA_CompatibleVersionText is now Basin Analysis GIS Ver 3.0 04/30/2016

Any settings files created prior to ver 3.0 will require that the version be manually updated to one of the above to load.

**Comment by jdduh** [comment]
I just found a bug. This has to wait before the bug is fixed. Sorry...

**Comment by lbross** [comment]
No problem. I plan to fix the bug shortly under the same version number so this was not throwaway work.
