### ISSUE TITLE
AOI Utilities - Add Selections to Map: layout displaced

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#45]
When adding a polyline layer to the map using the Add Selections to Map button, the layout frame disappears. I have to use the Zoom Whole Page tool to see the map layout. The Add Selections to Map seems to work fine with point data.

**Comment by lbross** [comment]
I updated the call to BA_DisplayVector to NOT zoom to the AOI. This appears to not work well in layout mode.  BA_MapDisplayPointMarkers which displays the points doesn't zoom to the AOI either. This will be in the next release of BAGIS V3.

**Comment by jdduh** [comment]
Displaying the raster also has the same problem.

**Comment by jdduh** [comment]
I think the display tool was designed with only the map view (not the layout view) in mind. Can you comment out the zoom to AOI statement? I might change my mind and decide to add it back later.

**Comment by lbross** [comment]
This is done. It will be in the next release of BAGIS V3. I added a parameter to BA_DisplayRaster to make zooming to the AOI optional
