### ISSUE TITLE
Auto pseudo site tool - new "Area meeting all constraints" layer and map layer setting

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#48]
Preserve the raster layer that represents the areas that meet all search constraints. Use this layer in the Auto-pseudo site tool's map layout. The other individual constraints are added to the layout, but are toggled off.

**Comment by lbross** [comment]
Do you want the "Area meeting all constraints" to include the represented area? It currently does not and adding it would require some additional manipulation of the data.

**Comment by jdduh** [comment]
Represented area doesn't meet the basic "search" constraint. Please don't add represented area to the area meeting all constraints. Please implement error handling routines when the "area meeting all constraints" is NULL. It might still be useful to keep individual constraint layers available for user's diagnostic purpose.

**Comment by lbross** [comment]
Sounds good. My implementation only uses the "Area meeting all constraints" layer if there is > 1 constraint selected. For example, if the user only selects elevation, the elevation layer will be activated and the "all constraints" layer will not be included on the map.
