### ISSUE TITLE
Generate Maps - data mix-up in the stelzone attribute table

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#49]
The names of snotel sites were not correctly transferred to the stelzone layer. See the images below. The other analysis layers seem to be correct.

Attribute table of layers.gdb/snotel_sites:
![image](https://user-images.githubusercontent.com/11510708/28800402-5d9c3796-7601-11e7-8621-0263beda2b31.png)

Attribute table of analysis.gdb/stelzone:
![image](https://user-images.githubusercontent.com/11510708/28800435-7b5579e6-7601-11e7-8315-9cd3e48db113.png)

![image](https://user-images.githubusercontent.com/11510708/28800391-4efc7f8e-7601-11e7-939a-9573ca42d4ac.png)

**Comment by lbross** [comment]
I suspect this is a bug in the ArcObjects api introduced during a later version. To populate the interval list, the code uses this function to get a list of all the elevations of the snotel sites:

pData = New DataStatistics
pData.Field = valuefieldname
pData.Cursor = pCursor
pEnumVar = pData.UniqueValues
          
However, some of the unique values that it returns are slightly off from the unique values returned in the ArcMap attribute table user interface. So, when it uses the elevation in a later query to get the snotel site name, the query fails to return any records. See below. The upper value is from ArcObjects. The lower value is from the ArcMap attribute table. You'll notice that two of them return the same value and those are the stations that worked in the stelzone layer. Any ideas on how to fix?

2775.69311523438
2775.693115234375 (Bear River)

2731.39379882813
2731.393798828125 (Crosho)

2870.1611328125    (Rabbit Ears)
2870.1611328125

3232.77416992188
3232.774169921875 (Tower)

2519.06787109375   (Dry Lake)
2519.06787109375

**Comment by jdduh** [comment]
"...when it uses the elevation in a later query to get the snotel site name..." this seems to be a bad practice (did I write that?) 
Given the number of decimal places of the elevation values, it's unlikely that two sites have the same elevation values (so the site name and elevation should both have unique values). Probably the correct way is to read both site name and elevation from the same source (e.g., snotel sites) and put them in a VB collection/list. Then use the records in the list to complete the analysis.

**Comment by lbross** [comment]
I did not write the code to get the snotel site name but I don't think it's bad practice to assume that the values returned by pData.UniqueValues can used successfully in a query statement. Also, we need to code defensively with the slight chance that two sites have the same elevation values. I will work out an updated algorithm and apply it to the snow course sites as well because it could have the same problem.

**Comment by lbross** [comment]
Current logic appears to support multiple sites with same elevation. Use all names for sites and separate multiples with ", ". We will replicate this.
