### ISSUE TITLE
How does IGXDialog work when selecting a web folder?

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis#5]
PRISM data is stored in a PRISM folder

**Comment by lbross** [comment]
Using GxFilterMapDatasetsLayersAndResults allows us to choose a map feature service. Example url that can be extracted: http://atlas.geog.pdx.edu/arcgis/services/AWDB_ALL/AWDB_SNOTEL_ALL/MapServer/FeatureServer.

But this is not the REST url that we use to work with the service. Maybe a subroutine to rewrite the url to the REST url?  http://atlas.geog.pdx.edu/arcgis/rest/services/AWDB_ALL/AWDB_SNOTEL_ALL/FeatureServer/0

May also iteratively query the REST url to get the layer id. In this example: 0

Question for Geoffrey: Can we assume the web services consumed by BAGIS v3 will be ArcGIS services? This makes things easier because there is a standard naming convention.

**Comment by lbross** [comment]
Another question for Geoffrey: Can we assume that our feature services will only have one layer? Otherwise we'll need to build a UI that's let's the user choose the layer by name. Example: atlasprod.sde_awdb.stations_SNTL

**Comment by jdduh** [comment]
Do our existing feature access services all have only one layer? If they do, then we can make it a design limitation on the feature services. The AWDB feature services are created and updated by Python scripts.

**Comment by lbross** [comment]
Our existing feature access services only have one layer. I will move forward assuming that this will continue to be the case.

**Comment by lbross** [comment]
Closing unless we add feature access services that have > one layer.
