### ISSUE TITLE
Include pseudo sites in the “tables” output from Maps/Tables screen

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis#54]
Open new issue separate from #50 as this could be implemented separately.

From Gus: Include pseudo sites in the “tables” output if I go back and rerun the tables, including area-elevation curve location, and elev-precip scatter plot.

From @jdduh: It's doable, but the current GUI needs to be expanded greatly to handle this capability.

**Comment by lbross** [comment]
What about adding a 'Tables' button to the Site Scenario too? We could produce a streamlined .xls that only includes charts directly related to sites. The tables would only include sites from scenario 1 although we could allow user to select scenario 2, if this added value. Following are charts we could publish:
1. Area-Elevation, Precipitation and Site Distribution: Include selected snow course, Snotel, and Pseudo-sites
2. Area-Elevation and Pseudo-site distribution (new)
3. Area-Elevation and Snotel/Snow course distribution (optional, differs from existing chart because it only includes sites selected in scenario 1)
4. Elev-Precip Chart: Add scenario 1 pseudo-sites to Sites in chart

Just thinking through how we might be able to do this ...

**Comment by lbross** [comment]
Per meeting with @jdduh (and confirmed by Gus) we will add a 'Tables' button to the Site scenario tool. We will only produce the Area-Elevation and Snotel/Snow course distribution (differs from existing chart because it only includes sites selected in scenario 1, including p-sites) and Elev-Precip Chart (including selected p-sites).

On the BAGIS Map Settings form, there is a checkbox to 'Generate Maps and Table for a Specified Elevation Range'. Does this generate a second set of maps and tables or does the elevation range overwrite the default settings? If it is a second set, we may have 3 new tables instead of 2?

**Comment by lbross** [comment]
Just verified that using the 'Specified Elevation Range' option DOES generate a second set of tables. Please confirm that this should also be supported with the new Site Scenario tables.

**Comment by lbross** [comment]
It seems we have to generate the zones rasters for each group of selected sites (snotel, snow course, pseudo) to generate the chart. Would these maps be useful for NWCC in another capacity? Maybe a pre-formatted map(s)?

Couple of other questions:
I can extract the site name and elevation from the scenario 1 grid on the site scenario screen to generate the site zones layers. This is faster than querying the layers. Also better because I can exclude un-selected sites from the analysis easily when I don't have to manipulate the layers. The only downside I can see it's slightly less precise because we round the elevation in the grid. But it is still to the closest foot/meter. Is this close enough?

I should delete the zones rasters for the selected sites if there is no further use for them. Please let me know.

**Comment by jdduh** [comment]
The site scenarios tool should not overwrite any layer created by the generate maps tool. I believe the mapping functions of the current site scenarios tool is sufficient for what NWCC wants. 

We can consider a way to improve the generate maps tool so that it can include pseudo sites (and subsets of snow courses and SNOTEL sites) in its table/map functions. We should store the "selected for analysis" attribute in the attribute tables of the snow courses, SNOTEL, and pseudo site featureclass. This could be an enhancement feature for next BAGIS version (i.e., next year).

**Comment by lbross** [comment]
The implementation of this is almost complete. All I have left to do is add the p-sites to the elev-precip table and chart. My code uses the layers from the generate maps tool but doesn't alter them in any way. I have gotten creative in using the information from the scenario 1 grid on the site scenarios tool to filter the information before adding it to the table.

We can talk about making the psite layer accessible in the generate maps tool, if you want.

The "selected for analysis" is stored in an xml configuration file in the maps folder but we can write it to the feature classes too, if you want. Wouldn't be too difficult.

**Comment by lbross** [comment]
Sharing an updated screenshot of the Site Scenarios form with the new Tables button. Tables is still not done. I need to add the p-sites. If you click on the help button next to the Tables button, here is the text that is shown: "Use the Generate Maps menu item to view/update the elevation interval, specified elevation range, or PRISM data settings that are used when generating the Site Scenario tables."

![image](https://user-images.githubusercontent.com/11527966/36814339-1561eb4c-1c8c-11e8-83b7-861f5a0963f8.png)

**Comment by lbross** [comment]
This is done and will be initially implemented in v3.2-b1

**Comment by jdduh** [comment]
Thanks! Let's not worry about showing p-sites on the generate maps tool.

**Comment by jdduh** [comment]
Here is a bug for this tool. The Excel Elev-Precip Chart doesn't have sites (and their regression equations) on it. The tool displayed a warning message saying that there is not enough data point to calculate the equation. The Elev_Precip_Sites spreadsheet is empty.

![image](https://user-images.githubusercontent.com/11510708/40504769-13475498-5f47-11e8-87c7-111d3505e581.png)

![image](https://user-images.githubusercontent.com/11510708/40504913-843d5c9c-5f47-11e8-8d0b-b3090a78b691.png)

**Comment by lbross** [comment]
I assume this is for the Tables button on the Maps Settings screen? Unfortunately I need you to upload the AOI to troubleshoot because it works fine on my test AOI.

**Comment by jdduh** [comment]
![image](https://user-images.githubusercontent.com/11510708/40505558-73568780-5f49-11e8-9870-6cad94f57eb4.png)

**Comment by jdduh** [comment]
Here are the screenshots from the Map Settings Table output. They are correct.
![image](https://user-images.githubusercontent.com/11510708/40505655-ccacbb06-5f49-11e8-805a-ebefe55bf887.png)
![image](https://user-images.githubusercontent.com/11510708/40505682-e0e62e7c-5f49-11e8-9855-019d921ba24e.png)

**Comment by lbross** [comment]
That one works for me too so I will still need the AOI :-( Does it have any pseudo-sites configured? If not, that might be the problem. My test AOI does.

**Comment by jdduh** [comment]
Mine doesn't have any pseudo site. The AOI is Animas R at Durango.

**Comment by jdduh** [comment]
If I add any pseudo site, then the Tables tool works normally.

**Comment by jdduh** [comment]
Now my AOI won't reproduce the error, even after removing the pseudo_site featureclass. I will create a new AOI and upload it to eBAGIS.

**Comment by jdduh** [comment]
You can donwload the AOI (Animas_R_at_Durango_Source) from https://ebagis.geog.pdx.edu/.

**Comment by lbross** [comment]
Thanks! Please let me know if any of these problems need to be resolved before I leave. I assume not but want to be sure. I'm mostly trying to gather information today while I can.

**Comment by jdduh** [comment]
I plan to let Gus play with the new site scenario tool so that we can get his feedback. None of these bugs seems to prevent from using the tool. You don't have to fix these bugs right away.

**Comment by lbross** [comment]
Sounds good. But this is fixed and will be in the next BAGIS add-in :-)

**Comment by jdduh** [comment]
Thanks! Please make another BAGIS release at the end of tomorrow.

**Comment by lbross** [comment]
Will do. I'm currently going through and setting the outWorkspace in all the places that you select a new Basin or AOI. I'm not sure that it will help. But I don't think it will hurt.
