### ISSUE TITLE
Setting From/To Elevation values for specified elevation range (maps)

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis#55]
It appears that the from/to values for specified elevation range on the Map Settings form must match one of the values in the 'click to set value' pick list. There is a UI existing for this purpose. However, the text boxes that it populates aren't read-only so the user can type in a value that will cause the table creation to fail. I recommend making these textboxes read-only.

Also, when trying to use the elevation range values on the Site Scenario tool to generate the new tables, if the units are different between the maps form and the site scenario form, we have a problem. For example, let's say the maps form uses feet and the lower range is 10000. If the site scenario form uses meters and we convert 10000 to 3048, it doesn't match any of the elevation range values causing the chart to fail. I recommend not creating the subrange elevation charts from the site scenario screen if the site scenario screen uses different units from the maps screen. We will provide an error/warning message to the user.

**Comment by lbross** [comment]
![image](https://user-images.githubusercontent.com/11527966/36610006-97cc68da-1883-11e8-9b67-baed8dce570c.png)

**Comment by jdduh** [comment]
Please make everything on the form read-only. Notify the user to rerun the generate maps tool to change the setting.

It would be nice to automatically switch between meters/feet if there is an inconsistency. I believe the generate maps form has a routine to do so. You can disable the automatic unit conversion for now and make it an enhancement feature later.

**Comment by lbross** [comment]
The Site Scenario form uses the ESRI.IUnitConverter to switch between meters/feet throughout the form. This results in slightly different output (hundredths) from the conversion routine that is used on the Generate Maps form. This is enough different to break the IntervalList when applying the specified elevation range after the min/max elevation has been converted. Switching either the Generate Maps or Site Scenario form so that they both use the same conversion routine would take a lot of time.

For the initial release, we will show this message if the units differ between the Site Scenario and Generate Maps forms: "The elevation units on the Generate Maps tool are feet. Specified Elevation Range will not be used! Change the units on this screen to match the Generate Maps tool to generate tables for the Specified Elevation Range."

The tables are still created except for the specified elevation range.

**Comment by lbross** [comment]
Found several text boxes on Generate Maps forms that should be read-only in addition to the specified elevation range. They contain reference data and shouldn't be edited by the user. Closing.
