### ISSUE TITLE
Consider combining the Generate Maps and Site Scenario tools

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis#56]
These tools share similar information and both produce tables and maps. Consider combining the tools, possibly with tabs. This is a future enhancement for the next project year.

**Comment by lbross** [comment]
The following fields are duplicated on the Generate Maps and Site Scenario tools:
- DEM elevation min and max
- Elevation unit (the tools should be adapted to use the same elevation unit setting)
- Maps button
- Tables button
- Settings read from the Generate Maps tool to generate Precipitation Correlation chart: Elevation unit, Elevation Interval, PRISM data selection, minimum PRISM value, whether a subrange is used including subrange to/from elevation, and aspect directions

The following fields are duplicated on the Generate Maps and Auto Site tools
- DEM elevation min, max, and range
- PRISM data select list
- PRISM data from / to select lists
- Precipitation min, max, and range
- Elevation unit (the tools should be adapted to use the same elevation unit setting)

**Comment by lbross** [comment]
Potential issues for combining these screens:
- The maps tool and site scenario tool use different algorithms for converting between meters and feet. The maps tool uses a conversion factor and the site scenario tool uses the ArcMap IUnitConverter. This is a problem when validating elevations against the DEM min/max. One of tools should be switched so they are both the same.
- The maps tool stores settings in a .txt file. The Site Scenario tool stores settings in a .xml file. These should be combined into a single file if the tools are combined. We could also consider adding logging for some of the settings that have been added since the maps tool logging was last updated. For example: Elevation Precipitation correlation settings. We could write a conversion routine that converts the maps .txt configuration file into the new format for older AOIs.

**Comment by jdduh** [comment]
We might have made a decision not to combine the tools but to implement separate "Map" and "Table" functions for the Site Scenario tool (or to disable some of the customization functions of the Generate Maps tool when it's activated from the Site Scenario tool). The tables/graphics to be implemented are:

- Area-Elevation, Precipitation  and Site Distribution
- Elev-Precip chart (scatter plot)

There will be 3 types of sites: SNOTEL, Snow Course, and Pseudo. We probably need to create a new site symbol for the pseudo site.

Will such a design prevents the potential issues from becoming real issues?

**Comment by jdduh** [comment]
For the Maps function on the Generate Maps dialog window, we can create a checkbox/radio button asking if user wants to use site scenario 1, 2, or NONE to plot the map. We can save flags in the attribute tables of SNOTEL, Snow Course, and pseudo site featureclasses. The flags indicate if a site was used in the scenarios. If scenario 1 or 2 is selected, then the Generate Maps function will use the flags in the attribute tables to perform the analysis.

**Comment by lbross** [comment]
I'm not sure that we ever made a conscious decision, but this is how things are currently implemented:
- There is a Tables button on the Site Scenario tool. This button generates tables/graphics using the sites selected in scenario 1 for the 2 tables/graphics you mentioned (Area-Elevation, Precipitation and Site Distribution, Elev-Precip chart (scatter plot)). It borrows settings from the Maps Settings tool when needed. For example: Precipitation Zone settings.
- Pseudo (Auto) Sites do have their own symbol on the Site Scenario maps, a pushpin
- The Maps Settings tool cannot be activated from the Site Scenario tool. It is a separate button.
- There is a Maps button on the Site Scenario tool that generates a series of maps specific to Site Selection and activates the associated toolbar buttons.
- There is also a Maps button on the auto site tool that generates a map for the most recent auto site

It sounds like you may want to make the following changes. Please review:
- Add a control to the Maps Settings tool that allows the user to use site scenario 1, 2 or None
- Restrict the Maps Settings analysis to the sites selected in the scenario. For example: # snow course sites in the elevation intervals grid would only include scenario 1 sites, snotel elevation zone rasters would only include selected sites.
- Would you want to add another column to the elevation zone grid for the pseudo sites? Another layer to the Data Status grid for pseudo site zones?
- Remove the Tables button from the Site Scenario form. Use only the selected scenario sites in the tables that are generated from the Maps Settings tool Tables button. Include pseudo sites in the tables if they are selected in the scenario. This includes the Elev-Precip chart (scatter plot). Add a new table for Area-Elevation and Pseudo Site Distribution. 
- Use only the selected scenario sites in the maps that are generated from the Maps Settings tool Maps button. Include selected scenario pseudo-sites if appropriate. 
- No changes to the Maps functions on the Site Scenario tool as they answer different business questions

It's a good idea to use the attribute tables to indicate if a site is used in a scenario. If we did this, we should re-do the site scenario logging so we're not storing the information in 2 places. If we move forward, I would like to convert the map_parameters.txt file to an .xml file and add the settings associated with the elevation precipitation correlation chart that we aren't currently logging. We will likely find additional items to add as we work through the design. I can write a conversion routine that will convert older map_parameters.txt files.

Let me know if you think I'm on the right track and I will start a design document on google docs that we can work on. Thanks!

**Comment by jdduh** [comment]
My current BAGIS V3 (3.1 L038) doesn't has the table button on the Site Scenario Tool. Maybe you had implemented what I need. Once I get a chance to use the new BAGIS V3, I will let you know if I have any enhancement request. Thanks!
