### ISSUE TITLE
Site Scenario Analysis Tool - Calculate Reclassify Error

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#59]
The process was performed on the original BAGIS V3.2-b1 on a freshly created AOI.

![image](https://user-images.githubusercontent.com/11510708/40515723-bfd697e4-5f62-11e8-88ae-f17e41eda92e.png)

A second error message showed up immediately after the first one. It seems to be caused by the first error.

![image](https://user-images.githubusercontent.com/11510708/40515749-d6ad490e-5f62-11e8-99d2-813eef60e959.png)

These pairs of error messages would repeatedly show up for all sites in the scenario.

**Comment by lbross** [comment]
Is this using the AOI that you just posted to basins today?

**Comment by jdduh** [comment]
The same AOI, but I had created several copies... I'm not switching back to the latest release of BAGIS V3.2-b1 (b1.1?) and see if the problem persists.

**Comment by jdduh** [comment]
I was able to reproduce the problem on b1.1. It seems that the problem is related to #58 (?). If the projection of the map layout is not set to Albers (USGS), then the error occurred. After setting the layout projection to Albers, then the Calculate tool worked fine.

**Comment by lbross** [comment]
How was it not in the right projection? I thought this was set when an AOI is selected?

**Comment by jdduh** [comment]
Try this:
1. Use the default settings on BAGIS (i.e., using webservices as the sources)
2. Start a new ArcMap session, use the Add Ref Layers" button to add the webservice layers to ArcMap. Now the projection of the layout should be in "WGS_1984_Web_Mercator_Auxiliary_Sphere."

I'm not sure why I used Web Mercator for the reference layers, but there must be a reason... probably ArcGIS Server doesn't support USA_Contiguous_Albers_Equal_Area_Conic_USGS_version?

**Comment by lbross** [comment]
Interesting. I would have thought that we would be resetting the map to the correct projection when an AOI is selected and the data frame name is set to Basin Analysis. I will look into this.

**Comment by jdduh** [comment]
Issue #58 interrupted the resetting. I wonder if there is a way to force the the resetting of layout projection even when the datum don't match.

**Comment by lbross** [comment]
This issue was resolved with the fix for issue #58. If the default projection cannot be set, you will no longer be able to get to this screen since you can't set the AOI. Setting the default projection is now required to successfully set the AOI.
