### ISSUE TITLE
Add (Automatic) Pseudo Site Tool - Close button doesn't work.

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#63]
User can only use the upper right "close" icon to close the dialog window.

**Comment by jdduh** [comment]
I'm puzzled. This seems to be related to the dual monitors setup on my computer. When ArcMap and the Add Pseudo Site tool are on different screen, then the Close button doesn't work. When they are on the same monitor, then it works.

**Comment by jdduh** [comment]
After further investigation, when the two monitors have different display resolution settings, then ArcGIS renders the GUI incorrectly. I believe this is an ArcGIS bug.

**Comment by lbross** [comment]
Closing. This is not something we can fix and I doubt ESRI will be releasing any bug fixes
