### ISSUE TITLE
Site Scenario Tool - perform the calculation only for areas within the AOI boundaries

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#64]
The tool currently perform the calculation using the whole buffered area. The calculation should be limited to the AOI boundaries. See the message from Gus for more information.

"I verified that the “represented area” in the report is the total of all represented area including in the buffer by calculating the area of the “represented area scenario 1” layer.  This is not correct and that layer should be trimmed to the AOI boundary for proper calculation and visualization.  The non-represented area seems to just be the difference between the represented area and the AOI area, which would explain why that number always adds up to the correct AOI area.
I suppose if you set a buffer of 0, then the represented area would be correct for the AOI, but really this should work consistently regardless of the buffer selected."

**Comment by lbross** [comment]
The represented area calculations are partially based on the filled_dem which is based on the buffered area. I will clip the npactual and nppseduo vectors to aoi_v before finalizing them. I will do this before creating the representation difference so that that layer is correct
