### ISSUE TITLE
Updates to reclipping and buffers

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis#65]
Start recording buffer distances in filled_dem and prism layers when an AOI is created. Add capability to update these distances and reclip PRISM, Snotel, and Snow Course layers in an existing AOI. Record buffer distances when these layers are reclipped.

See [design document on google drive](https://drive.google.com/open?id=1PmMAoYejIhC_KAWTBWlOrKkArXFr3gKB3tZv3EzKDXk) for details. @jdduh: Please review/edit/approve the design document so I can get started on coding.

**Comment by jdduh** [comment]
The spec looks good. I have put some comments.

**Comment by lbross** [comment]
I agree with and have incorporated most of your comments. Recording the buffer distance from the beginning in the snotel and sc layers simplifies some other aspects of the processing. My only remaining question is where to put the original copies of the snotel and sc layers? Are you OK with leaving them in the layers.gdb and having them show up in some of the BAGIS-H and BAGIS-P tools? If so, what do you suggest for a re-naming convention?
The other option is to create a new file .gdb like 'backup.gdb', but this wouldn't be included in any eBAGIS uploads, which you have indicated is a requirement.

**Comment by lbross** [comment]
I am using the BA_AOIClipBuffer global variable as the source for the buffer distances for the filled_dem, snotel and snow course layers. It looks like if the analyst unchecks the buffer checkbox, this variable is set to 1 and I am recording that distance. OK?

Also, do we want to continue to hide the PRISM buffer distance on frmCreateAOI or frmCreateAOIBnd if we are going to make it visible on the AOI Utilities form? Currently the analyst has to know to double-click on the buffer distance label to see a dialog that allows them to update this distance.

**Comment by lbross** [comment]
Please review slide 5 for proposed new AOI Utilities screen

**Comment by jdduh** [comment]
The updated GUI looks good. Thanks!

**Comment by jdduh** [comment]
When the user sets the buffer distance to zero, BAGIS internally set the dem clipping buffer distance to 1 meter. A buffer distance of 0 won't work for AOIs with dangling parts (that are connected to the main AOI by a corner, instead of an edge).

Please reveal PRISM clipping buffer distance adjusting GUI. The reason we hide it is to prevent users setting the buffer distance too small. A small PRISM buffer distance will produce missing data (NODATA) in the AOI in subsequent basin analyses.

**Comment by jdduh** [comment]
How about renaming the original SNOTEL and SC layers with "_original" suffix and put them in the same GDB?

**Comment by lbross** [comment]
I suggest renaming the original snotel and sc layers with "original_" prefix. This should mean less of a chance of the user choosing them by accident in a layer listing. They won't be right next to the current snotel layers and 'original' will be clearly visible in the list and won't be cut-off on the right-hand side.

**Comment by jdduh** [comment]
Agree. Please use original_ as the prefix.

**Comment by lbross** [comment]
Please review p 3 and 4 of the design spec for revised GUI for the AOI creation screens. The PRISM buffer is now visible to edit.

**Comment by lbross** [comment]
I'm adding code to create a new buffered AOI feature class if the reclip buffer for the snotel file(s) differs from aoib_v. When reviewing existing code for the same task for the prism reclip, I ran across these comments:
```
'save the buffered AOI as a shapefile and then import it into the GDB
'to prevent a bug when the buffer distance exceed the xy domain limits of the GDB
'Copy the temporary line shape file to the aoi.gdb
```
Do you recommend these extra steps for the new snotel reclip buffer(s)? Also, I plan to delete the snotel reclip buffer(s) when I'm done using them. Do you see any reason to keep them in the aoi.gdb?

**Comment by jdduh** [comment]
The updated GUI looks good. Just wonder why the PRISM buffer on one of the slide is 1500 meters. I suggest that we keep these buffered clipping polygons (similar to the p_aoi and p_aoi_v layers that we keep for clipping the PRISM layers). Maybe use st_ prefix for SNOTEL and sc_ prefix for SC.

I'm not sure if the bug has been fixed. Please use these extra steps unless you want to test it out.

**Comment by lbross** [comment]
The PRISM buffer on one of the slides was 1500 because I was testing different distances. Also to make sure the distance was being read from  the layer metadata rather than just using the default. I will keep the buffered clipping polygons: st_aoi_v and sc_aoi_v. Note that I don't create sc_aoi_v if snotel and snow course have the same buffer distance. I re-use st_aoi_v.

I will add the buffer distance tags to st_aoi_v and sc_aoi_v. This way if the user reclips without changing the buffer distance, we can re-use the layers. 

I did use the aforementioned extra steps when creating the new snotel reclip buffer(s).

I tested the elev-precip correlation function with dem, snotel, and snow course all at different extents and it seemed to work OK.

**Comment by lbross** [comment]
I changed my mind about trying to re-use pre-existing st_aoi_v and sc_aoi_v layers if the user reclips without changing the buffer distance. It gets confusing trying to manage these layers and I don't want to incorrectly use them if they are hanging around from an previous analysis. I am recording the buffer distance in the tags.
