### ISSUE TITLE
Title in wrong place when maps are generated

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis#67]
When you run the Maps dialog immediately after creating an AOI the map title is outside of the map frame. If you run the maps tool after changing to a new AOI, it is fine. Problem occurs on both versions of AGS

**Comment by lbross** [comment]
![maptitle](https://user-images.githubusercontent.com/11527966/48652187-0eb59880-e9b3-11e8-90d0-f738c34bb5c2.png)

**Comment by jdduh** [comment]
If the AOI name is shorter, then this won't happen. BAGIS users are expected to know how to fix this manually with ArcGIS layout tools. Alternatively, we can move the title a little lower when creating it. The placement is determined in VB codes.

**Comment by lbross** [comment]
My concern was that the placement is better when you run the maps tool on an existing AOI rather than running it on an new AOI immediate after creating the AOI (in the same session). Upon closer examination it appears that if you have a basin selected, the basin title is appended to the AOI name, making it longer. When I select an AOI using the AOI Info tool, a basin isn't selected so it isn't appended to the title. See image below. Do we want to continue to include the basin in the map title even though it is inconsistent, depending on how the AOI is selected?
![maptitle](https://user-images.githubusercontent.com/11527966/48726471-4eaf9200-ebe4-11e8-9078-b06c6921f47a.png)

**Comment by jdduh** [comment]
Good observation! Please remove the basin name from the title. The basin-aoi hierarchical structure is not enforced by the end user.

**Comment by lbross** [comment]
Set basin_name to empty string before setting title on map. This way behavior is consistent but we can add the basin name back in if need be
