### ISSUE TITLE
Updates to BAGIS settings to support ArcGIS Online

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis#69]
We will start hosting the gauge station, snotel, and snow course layers on ArcGIS Online. The ArcMap API does not provide a browse function that allows the users to locate and select layers from ArcGIS Online. In lieu of this, we will make the text boxes for these three layers editable so the user can input the rest URLs. The easiest way to do this is to copy the url from the bottom right-hand corner of the feature services details page on ArcGIS Online.

Because we are allowing freeform text, we need to add some validation for these fields. We will check to see if a layer id is specified. ie: /0 at the end of the url. If not, we will add /0 (the first layer) as the default. The url from ArcGIS online doesn't include a layer id. Then we will check to see if the url is valid before allowing the user to save the settings. These validations will continue to work for layers that we host at PSU on basins.

We will also need to update the Default Settings for these layers when we are ready to cut over to them.

**Comment by jdduh** [comment]
See #73.
