### ISSUE TITLE
Define p-site with same settings fails

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis#70]
when an AOI is moved from one path to another. We store the full path to the source for the Proximity and Location layers in the psite log. This means that if you move an AOI and try to generate a new site from the constraints of an existing one, it will fail. For example, in my testing the path to the proximity layer source in the psite log is E:\NWCC\AOIs\from_george\yampa_PSU\yampa_AOI\layers.gdb\FSRoads_Albers. But on my computer it should be C:\Docs\yampa_AOI\layers.gdb\FSRoads_Albers.

We will store the relative path going forward but also add code to parse the full path so that it can be used from legacy p-sites.

**Comment by lbross** [comment]
Change of plans. We will still store the full path in the log but will validate and modify it as needed when copying p-site constraints. Since we would have to support both full and relative paths indefinitely, this approach is less work

**Comment by lbross** [comment]
Gus' problem is that we added the BA_STYPE field to the pseudo_sites feature class when adding pseudo sites to the elev-precip correlation charts. However, we didn't add a check to the pseudo-sites creation code to add this column to any old pseudo_sites tables that didn't have it. I will fix

**Comment by jdduh** [comment]
Got it. What's logic of using pseudo-sites in the Generate Maps tool? I don't see any GUI change on the dialog window.

**Comment by lbross** [comment]
I add to refresh my memory. We did not integrate pseudo-sites with the Generate Maps tool because there was no way to tell if a site should be included in the analysis or not. We added a Tables button to the Site Scenario tool which generates an elevation distribution chart and an elevation precip scatterplot for the selected sites only. Selected sites may include any combination of snotel, snow course, or pseudo.

Note that I'm finding some inconsistencies with displaying the units/values correctly when loading a pseudo site log and am also fixing that.

**Comment by lbross** [comment]
The units for the buffer/proximity layers have been recorded incorrectly. For some reason I used our MeasurementUnit enumeration in some places and the esriUnits enumeration in others. The VB editor did not warn me. It seems that enumerations in VB are not typesafe :-( I've spent some time trying to handle the incorrect units but the stored values are inconsistent. I think it's best to just tell the users that this was a problem and to move forward correctly.

The only time this poses an operational problem is when re-using constraints from an existing p-site. I found the problem when ArcMap tried to execute a buffer of 5000 miles instead of 5000 meters. When the users re-use constraints, if there is a proximity constraint, they just need to check the distance and units to see if it is reasonable. They can edit the distance if they need to.

**Comment by lbross** [comment]
Looks like the elevation reclass won't work if the p-site form is being viewed with elevation layers in feet. I suspect it is a problem with rounding the min and max of the dem after converting the display to meters. I think the actual value is stored somewhere in the SiteScenario or PseudoSite form so I will try to pull it from there rather than converting.

Update: I was rounding the min and max to the nearest integer which is too aggressive. I updated to 5 decimal places and that seems to work. It is stored in the same units as the form is using
