### ISSUE TITLE
TLS 1.2 Immediate Action Required — ArcGIS Security Update

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#73]
ArcGIS Desktop 10.6 or prior versions need a patch to be compatible with TLS 1.2
https://support.esri.com/en/tls

Though unfortunately this important security update does not comply with our academic calendars, action must be taken to ensure smooth transition… please visit the main TLS page for further details and next steps.

Q. I have ArcGIS Pro 2.3, am I ready to go for April 16?
A. Yes.

Q. I have ArcGIS Pro 1.2 and earlier, am I ready to go for April 16?
A. No, action must be taken.

Q. I have ArcGIS Map 10.7, am I ready to go for April 16?
A. Yes.

Q. I have ArcGIS Map 10.6.1 and earlier, am I ready to go for April 16?
A. No, action must be taken.
A2. Perhaps an opportunity to update workflows to utilize ArcGIS Pro.

Q. I have ArcGIS Enterprise version 10.6, am I ready to go for April 16?
A. It depends, likely action must be taken. Version of Portal for ArcGIS higher than 10.4.1 are unaffected. Versions of ArcGIS Server are dependent on underlining OS.

**Comment by lbross** [comment]
I'm not sure what needs to be done here besides making sure that my ArcMap client is patched. I don't know that BAGIS would be affected by TLS because all the data sources are public and don't require user name/password. Is there anything else you can think of? Of course, we will test after April 16 to make sure everything still works.

**Comment by lbross** [comment]
Per the bulletin, users running ArcMap 10.6.1 or older will need to install a patch to continue using ArcGIS online from ArcMap. I am using 10.5.1. I found that I could not use ArcGIS online services from BAGIS V3 without installing this patch. The patch takes a long time to install. I think it is a full installation. Closing
