### ISSUE TITLE
Dealing with large forms on a tiny screen

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#76]
When a form is too large to fit on a computer screen (e.g., 1024 x 768), users cannot access some of the required functions (i.e., buttons) on the form. One example is the auto pseudo site tool. If the computer screen is too small, the resized the form won't allow users to access the "1. find site" button. Is there a way to enable a scroll bar on the form? 

![image](https://user-images.githubusercontent.com/11510708/66521786-c0b0f400-eaa0-11e9-90ef-af09d4f3d8a4.png)

**Comment by jdduh** [comment]
Can you adjust the dialog window layout so that it fits on a 1024 x 768 screen? See the image below for an example. This is a temporary fix before a better dialog configuration is found.

![image](https://user-images.githubusercontent.com/11510708/67056122-b5447500-f0ff-11e9-8789-e68afe85e09d.png)

**Comment by lbross** [comment]
I enabled the autoscrollbars parameter to add scrollbars to this form. I also pulled the controls a little closer together. There is a new version of the add-in posted to basins. I updated the compile date but not the release. We are still working on v3.4-b2. Please let me know if this helps.

**Comment by jdduh** [comment]
The scrollbars work fine.
