### ISSUE TITLE
AGOL TLS 1.2 impact - Unable to save the settings when using default settings

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#80]
Using BAGIS 3.4 b2 on ArcMap 10.5.1. The URL to the gauge station is:

https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/stations_USGS_ACTIVE/FeatureServer/0

![image](https://user-images.githubusercontent.com/11510708/79714758-a42f1900-8286-11ea-9de0-fbd02199db58.png)

**Comment by lbross** [comment]
I checked the url to make sure it is correct; ie: pointed to nrcs.maps.arcgis.com and it is. I was able to successfully load and save the default settings this morning. I wonder if arcgis.com was having problems over the weekend? Please try again and let me know how it goes.

**Comment by jdduh** [comment]
Is it related to the awdb_id field missing from the stations_USGS_ACTIVE layer?

![image](https://user-images.githubusercontent.com/11510708/79781904-150c1a80-82f3-11ea-9399-68539af5c889.png)

I downloaded the stations_USGS_ACTIVE from NRCS NWCC ArcGIS Hub. When using that layer as the gauge station layer, BAGIS gave me this error message.

![image](https://user-images.githubusercontent.com/11510708/79782421-e80c3780-82f3-11ea-8bea-667243811fd8.png)

**Comment by lbross** [comment]
This makes no sense to me. Assume you are getting these errors this morning. I was just able to successfully load/save the settings. All it is looking for when loading the settings is a feature service that it can connect to. Can you send me your basinanalyst.def?

Also, what version of ArcMap are you using? I am testing on 10.5.

Are you trying to use awdb_id for the name? Our default settings have 'name' for the name field. It looks like awdb_id has never been a field in the usgs web service. Take a look at issue #79 and see if that provides some clarification. If the 'name' field is set to a field that doesn't exist on the web service, that would probably prevent it from validating.

**Comment by jdduh** [comment]
I'm using 10.5.1 with BAGIS 3.4 b2. My basinanalyst.def file is attached. I'm sure that the webservice was working when the error occurred.

[basinanalyst.txt](https://github.com/PSU-CSAR/vb-bagis/files/4505803/basinanalyst.txt)

**Comment by jdduh** [comment]
If I manually edit the basinanalyst.def file and put the webservice as the gauge station source data, then I got this error message. My ArcMap is not connected to any enterprise AGOL.

![image](https://user-images.githubusercontent.com/11510708/79794162-a6d15300-8306-11ea-8183-335f64bb7ed8.png)

**Comment by jdduh** [comment]
This is the BAGIS version that I have. Is there a newer version?
![image](https://user-images.githubusercontent.com/11510708/79794494-31b24d80-8307-11ea-9ada-0e8cd3142d3f.png)

This is the information shown in the Addin Manger.
![image](https://user-images.githubusercontent.com/11510708/79794632-763de900-8307-11ea-8e70-04c82b1a3d94.png)

**Comment by lbross** [comment]
Yes. There is a newer version. I wonder if your ArcMap is holding onto this old version for some reason? Make sure it is completely gone before trying to install the latest version from the FTP server. The latest version is BAGIS_3.4-b3.esriAddIn from Feb 20 of this year. I also uploaded my basinanalyst.def file (that works) to the same folder as the add-in on basins: /BAGIS/BAGIS_addins/For ArcGIS10.5.X and later

Please let me know if upgrading to the newer version helps.

**Comment by jdduh** [comment]
Still no luck! Can you confirm that the latest BAGIS release's About dialog window still shows Release 3.2 (L039)? This is such a bizarre puzzle! I will do more troubleshooting and report back.

![image](https://user-images.githubusercontent.com/11510708/79799156-df752a80-830e-11ea-9cf6-cc050a5d329f.png)

**Comment by jdduh** [comment]
This must be related to ArcGIS Online's switch to TLS 1.2. I'm patching my 10.5.1 and will close the case if that was the cause.

https://community.esri.com/thread/233094-underlying-connection-was-closed-while-loading-content-from-agol

**Comment by jdduh** [comment]
Mystery solved. The TLS 1.2 patch resolved the problem. Sorry for causing the confusion...

**Comment by lbross** [comment]
Good sleuthing! Now we just need to remember this solution if a user encounters this problem :-)
