### ISSUE TITLE
Clipping ImageService to vector

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis#9]
I have found that image services can't be clipped to vectors because you have to provide the number of cells on each axis (rows & columns). For now, I will write a subroutine that converts a vector to a raster prior to clipping and then deletes it when clipping is complete. For BAGIS V3, we keep a raster copy of the aoi_v so we may want to re-think the workflow.

**Comment by lbross** [comment]
Don't forget about snap raster

**Comment by lbross** [comment]
Closing. Re-wrote function so we calculate the rows/columns from the cell size and vector extent before clipping. No need to convert vector to raster.

**Comment by jdduh** [comment]
Not sure if this bug should go here. Anyway, here is the description.

When the PRISM layers were clipped to the AOI, their cell size changed. This probably is related to the snap raster/processing extent settings of the geoprocessor. The correct behavior should ensure that the clipped PRISM layers have the same cell size and cell location of the source PRISM layers.

Here is a screenshot of the source PRISM layer on webservices (basins) server.
![image](https://cloud.githubusercontent.com/assets/11510708/24673644/ddc51450-192d-11e7-8636-992116245450.png)

Here is a screenshot of the PRISM layer of the Animas AOI.
![image](https://cloud.githubusercontent.com/assets/11510708/24673704/13806748-192e-11e7-8d67-eca7204f54b2.png)

The AOI's definition file (basinanalyst.def) contents are:
Basin Analysis GIS Ver 3.0 04/30/2016
E:\NWCC\GIS\Static\Reference_Data\US_DEM15sec\US_ShadedRelief_300Multi.lyr
E:\NWCC\GIS\Static\Reference_Data\US_Hydro\EPA_RF1_Hydro.lyr
E:\NWCC\GIS\Static\Reference_Data\US_Hydro\USGS_HUC8.lyr
E:\NWCC\GIS\Static\DEM\WESTUS_BC_30M\westus_bc_30m
http://basins.geog.pdx.edu/arcgis/services/BAGIS_GISLayers/DEM_westus_bc_30m/ImageServer
False
True
http://webservices.geog.pdx.edu/arcgis/rest/services/AWDB_ACTIVE/stations_USGS_ACTIVE/FeatureServer/0
name
basinarea
Sq. Miles
http://webservices.geog.pdx.edu/arcgis/rest/services/AWDB_ACTIVE/stations_SNTL_ACTIVE/FeatureServer/0
elevation
name
False
http://webservices.geog.pdx.edu/arcgis/rest/services/AWDB_ACTIVE/stations_SNOW_ACTIVE/FeatureServer/0
elevation
name
False
http://webservices.geog.pdx.edu/arcgis/services/BAGIS_PRISM

**Comment by lbross** [comment]
Clipping an image service works differently than a local raster. I supply the number of columns/rows that I want and the extent. Then I save the result locally. I am working with a vector (p_aoi_v). What I suspect is happening is that the extent from the vector isn't quite large enough to accommodate the number of cells I'm requesting, so ArcGIS server is adjusting the resolution to make it fit. Somehow we need to provide an extent that matches the cell size. Any ideas?

Here is the code that currently gets the information where features is the vector feature class:
            If features IsNot Nothing Then
                extent = features.Extent
                xColumns = CLng(Math.Ceiling(extent.Width / xCellSize))
                yRows = CLng(Math.Ceiling(extent.Height / yCellSize))
            End If

**Comment by jdduh** [comment]
Is there a way to change the extent values? You can reset the XMin, YMin, XMax, and YMax using the following formulas:
newextent.XMin = PRISMextent.XMin + Math.Truncate((extent.XMin - PRISMextent.XMin) / xCellSize) * xCellSize
newextent.YMin = PRISMextent.YMin + Math.Truncate((extent.YMin - PRISMextent.YMin) / yCellSize) * yCellSize
newextent.XMax = newextend.XMin + xCellSize * XColumns
newextent.YMax = newextend.YMin + yCellSize * yRows

**Comment by jdduh** [comment]
Use the original formulas for xColumns and yRows.

**Comment by lbross** [comment]
Should be able to do this. I'm unsure of the distinction/source between PRISMextent and extent in your formula. I am currently starting with the extent of p_aoi_v.

**Comment by lbross** [comment]
This should be fixed using this formula, where the original extent is the extent of p_aoi_v. Good suggestion! This will be in the next release of BAGIS v3.

            'Reset extent max to accomodate cell size
            Dim aPoint As IPnt = imageRasterProps.MeanCellSize
            extent.XMax = extent.XMin + aPoint.X * xCols
            extent.YMax = extent.YMin + aPoint.Y * yRows

![cellsize](https://cloud.githubusercontent.com/assets/11527966/24718740/f1b9000c-19eb-11e7-9b49-35edfeedf920.png)

**Comment by jdduh** [comment]
The PRISMextent is the map extent of the source PRISM layer. The extent is the p_aoi_v extent. The formulas that I provide could align the clipped raster with the source PRISM raster. Your modified formulas might create an offset of the cell alignment.

**Comment by lbross** [comment]
This works, almost. When I lay the p_aoi_v on top of the new raster, it isn't completely covered by the raster. Should I just add 1 to the X and Y cell counts? I also don't know how to tell if the cell alignment is off. When I try to line it up with the web service, the symbology for the web service doesn't show the individual cells.

**Comment by jdduh** [comment]
Please add 1 to row and col. 
To view cell boundaries, please change the resampling to nearest neighbor.
![image](https://cloud.githubusercontent.com/assets/11510708/24726108/1140934e-1a06-11e7-9d00-96f160e34f20.png)

You can also set the symbology to discrete color.
![image](https://cloud.githubusercontent.com/assets/11510708/24726161/36d98462-1a06-11e7-93cf-d9079e5ace6d.png)

**Comment by lbross** [comment]
This is done. Changing the resampling was the key to viewing the cell boundaries. This will be in the next version of BAGIS V3.
